source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’8.4’
use_frameworks!

target 'Cake' do
	pod 'AWSCognitoIdentityProvider', '~> 2.4.16'
	pod 'AWSCore', '~> 2.4.16'
	pod 'IQKeyboardManager'
	pod 'JGActionSheet'
	pod 'JVFloatLabeledTextField'
	pod 'NYAlertViewController'
	pod 'MGSwipeTableCell', '~> 1.5'
	pod 'RESideMenu', '~> 4.0.7'
	pod 'SVProgressHUD'
	pod 'UITextField+Shake', '~> 1.1'
	pod 'YYWebImage'
end

target 'CakeTests' do

end

target 'CakeUITests' do

end

